name: ci

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: ${{matrix.type.name}} ${{matrix.config.name}}
    runs-on: ubuntu-latest
    container: ghcr.io/griswaldbrooks/marky:upstream
    env:
      CCACHE_DIR: ${{ github.workspace }}/.ccache
    strategy:
      fail-fast: false
      matrix:
        preset: [debug, release, coverage]
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Cache ccache
        uses: pat-s/always-upload-cache@v3
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ccache-cmake-${{ matrix.preset }}-${{ github.sha }}-${{ github.run_id }}
          restore-keys: |
            ccache-cmake-${{ matrix.preset }}-${{ github.sha }}
            ccache-cmake-${{ matrix.preset }}
    - name: Configure
      run: cmake --preset ${{ matrix.preset }} 

    - name: Build
      run: cmake --build build/${{ matrix.preset }} 

    - name: Test
      run: ctest --test-dir build/${{ matrix.preset }} --output-on-failure 

    - name: Benchmark
      run: ./build/benchmarks/benchmark_geometry --benchmark_format=json | tee benchmark_result.json
 
    - name: Download previous benchmark data
      uses: actions/cache@v4
      with:
        path: ./cache
        key: ${{ runner.os }}-benchmark
  
    - name: Store benchmark result
      uses: benchmark-action/github-action-benchmark@v1
      with:
        tool: 'googlecpp'
        output-file-path: benchmark_result.json
        external-data-json-path: ./cache/benchmark-data.json
        fail-on-alert: true
        github-token: ${{ secrets.GITHUB_TOKEN }}
        comment-on-alert: true
        summary-always: true
        alert-comment-cc-users: '@griswaldbrooks'
