name: ci

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: ${{matrix.type.name}} ${{matrix.config.name}}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        type:
        - { name: Shared, flags: "ON" }
        - { name: Static, flags: "OFF" }
        config:
        - { name: Debug }
        - { name: Release }
    container: ghcr.io/griswaldbrooks/marky:upstream
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure
      run: cmake -B build -DBUILD_SHARED_LIBS=${{matrix.type.flags}} -DCMAKE_BUILD_TYPE=${{matrix.config.name}}

    - name: Build
      run: cmake --build build --config ${{matrix.config.name}}

    - name: Test
      run: ctest --test-dir build --output-on-failure --build-config ${{matrix.config.name}}
