name: ci

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: ${{matrix.type.name}} ${{matrix.config.name}}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        type:
        - { name: Shared, flags: "ON" }
        - { name: Static, flags: "OFF" }
        config:
        - { name: Debug }
        - { name: Release }
    container: ghcr.io/griswaldbrooks/marky:upstream
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure
      run: cmake -B build -DBUILD_SHARED_LIBS=${{matrix.type.flags}} -DCMAKE_BUILD_TYPE=${{matrix.config.name}}

    - name: Build
      run: cmake --build build --config ${{matrix.config.name}}

    - name: Test
      run: ctest --test-dir build --output-on-failure --build-config ${{matrix.config.name}}

    - name: Benchmark
      run: ./build/benchmarks/benchmark_geometry --benchmark_format=json | tee benchmark_result.json
 
    - name: Download previous benchmark data
      uses: actions/cache@v4
      with:
        path: ./cache
        key: ${{ runner.os }}-benchmark
  
    - name: Store benchmark result
      uses: benchmark-action/github-action-benchmark@v1
      with:
        tool: 'googlecpp'
        output-file-path: benchmark_result.json
        external-data-json-path: ./cache/benchmark-data.json
        fail-on-alert: true
        github-token: ${{ secrets.GITHUB_TOKEN }}
        comment-on-alert: true
        summary-always: true
        alert-comment-cc-users: '@griswaldbrooks'
